name: run tests
on: [ push ]


jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ledgerhq/ledger-app-builder:latest
      volumes:
        - /data/apps:/app
    steps:
      - name: update nanos sdk
        run: cd $BOLOS_SDK && git checkout master && git pull
      - name: get ledger-app code
        run: cd /app && git clone https://github.com/PlatONnetwork/ledger-app-platon.git
      - name: build ledger-app
        run: cd /app/ledger-app-platon && make

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: get emulator
        run: docker pull ledgerhq/speculos:latest
      - name: debug
        run: ls /data
      - name: run emulator
        run: docker run -v /data/apps/ledger-app-platon/bin:/speculos/apps --publish 41000:41000 ledgerhq/speculos --display headless --vnc-port 41000 apps/app.elf
      - name: run tests
        run: cd /speculos/apps/ledger-app-platon && pip install requments.txt && pytest
