name: run tests
on: [ push ]


jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ledgerhq/ledger-app-builder:latest
      volumes:
        - /data/app:/app
    steps:
      - name: update nanos sdk
        run: cd $BOLOS_SDK && git checkout master && git pull
      - name: get ledger-app code
        run: cd /app && git clone https://github.com/PlatONnetwork/ledger-app-platon.git
      - name: build ledger-app
        run: cd /app/ledger-app-platon && make
      - name: upload ledger-app
        uses: actions/upload-artifact@v2
        with:
          name: app.elf
          path: /app/ledger-app-platon/bin/app.elf

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: download ledger-app
        uses: actions/download-artifact@v2
        with:
          name: app.elf
          path: /data/apps
      - name: debug
        run: ls /data
      - name: get emulator
        run: docker pull ledgerhq/speculos:latest
      - name: run emulator
        run: docker run -v /data/apps:/speculos/apps --publish 41000:41000 ledgerhq/speculos --display headless --vnc-port 41000 apps/app.elf
      - name: get ledger-app code
        run: cd ~ && git clone https://github.com/PlatONnetwork/ledger-app-platon.git
      - name: run tests
        run: cd ~/ledger-app-platon && pip install requments.txt && pytest
